using System;
using System.Linq;
using DTOMaker.SrcGen.Core;
namespace DTOMaker.SrcGen.MemBlocks;
#pragma warning disable CS0162 // Unreachable code detected
public partial class EntityGenerator
{
    protected override void OnGenerate(OutputEntity entity)
    {
        using var entityScope = NewScope(entity);
        Emit("// <copyright>");
        Emit("//     Copyright (c) T_CopyrightYear_. All rights reserved by T_CopyrightOwner_.");
        Emit("// </copyright>");
        Emit("// <auto-generated>");
        Emit("//     This source file was generated by a DTOMaker source generator. Changes made to this file will be lost");
        Emit("//     if re-generated. For further information, refer to: https://github.com/datafac/dtomaker-all.");
        Emit("// </auto-generated>");
        Emit("#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required");
        Emit("#nullable enable");
        Emit("using DataFac.Memory;");
        Emit("using DTOMaker.Models;");
        Emit("using DTOMaker.Runtime.MemBlocks;");
        Emit("using DataFac.Storage;");
        Emit("using System;");
        Emit("using System.Buffers;");
        Emit("using System.Runtime.CompilerServices;");
        Emit("using System.Runtime.InteropServices;");
        Emit("using System.Text;");
        Emit("using System.Threading.Tasks;");
        Emit("using T_ImplNameSpace_;");
        if (false)
        {
            Emit("using T_CustomMemberType_ = System.DayOfWeek;");
            Emit("using T_NativeMemberType_ = System.Int32;");
            Emit("namespace DataFac.Memory");
            Emit("{");
            Emit("    public static class Codec_T_NativeMemberType__T_MemberBELE_");
            Emit("    {");
            Emit("        public static T_NativeMemberType_ ReadFromSpan(ReadOnlySpan<byte> source) => Codec_Int32_LE.ReadFromSpan(source);");
            Emit("        public static void WriteToSpan(Span<byte> source, T_NativeMemberType_ value) => Codec_Int32_LE.WriteToSpan(source, value);");
            Emit("    }");
            Emit("}");
            Emit("namespace T_MemberTypeImplSpace_");
            Emit("{");
            Emit("    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_");
            Emit("    {");
            Emit("        private const int ClassHeight = 1;");
            Emit("        private const int BlockLength = 8;");
            Emit("        private const long StructureCode = 0x00_41L;");
            Emit("        private static readonly BlockHeader _header = BlockHeader.CreateNew(3, StructureCode);");
            Emit("");
            Emit("        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeImplName_ source)");
            Emit("        {");
            Emit("            if (source.IsFrozen) return source;");
            Emit("            return new T_MemberTypeImplName_(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeImplName_? source)");
            Emit("        {");
            Emit("            return (source is null) ? null : CreateRequired(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)");
            Emit("        {");
            Emit("            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;");
            Emit("            return new T_MemberTypeImplName_(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? source)");
            Emit("        {");
            Emit("            return (source is null) ? null : CreateRequired(source);");
            Emit("        }");
            Emit("        public static T_MemberTypeImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)");
            Emit("        {");
            Emit("            return new T_MemberTypeImplName_(buffers);");
            Emit("        }");
            Emit("        private readonly Memory<byte> _writableLocalBlock;");
            Emit("        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;");
            Emit("        public T_MemberTypeImplName_() : base(_header)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) : base(_header, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) : base(_header, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("            this.Field1 = source.Field1;");
            Emit("        }");
            Emit("        protected T_MemberTypeImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(_header, sourceBlocks)");
            Emit("        {");
            Emit("            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];");
            Emit("            if (sourceBlock.Length < BlockLength)");
            Emit("            {");
            Emit("                // source too small - allocate new");
            Emit("                _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("                sourceBlock.CopyTo(_writableLocalBlock);");
            Emit("            }");
            Emit("            else");
            Emit("            {");
            Emit("                _readonlyLocalBlock = sourceBlock;");
            Emit("                _writableLocalBlock = Memory<byte>.Empty;");
            Emit("            }");
            Emit("        }");
            Emit("        public T_MemberTypeImplName_(ReadOnlySequence<byte> buffers) : this(_header, SourceBlocks.ParseFrom(buffers)) { }");
            Emit("");
            Emit("        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);");
            Emit("        protected override IEntityBase OnPartCopy() => throw new NotImplementedException();");
            Emit("        protected override int OnGetEntityId() => 3;");
            Emit("        protected override int OnGetClassHeight() => ClassHeight;");
            Emit("        protected override ValueTask OnPack(IDataStore dataStore) => default;");
            Emit("        protected override ValueTask OnUnpack(IDataStore dataStore, int depth) => default;");
            Emit("");
            Emit("        public Int64 Field1");
            Emit("        {");
            Emit("            get => Codec_Int64_LE.ReadFromSpan(_readonlyLocalBlock.Slice(0, 8).Span);");
            Emit("            set => Codec_Int64_LE.WriteToSpan(_writableLocalBlock.Slice(0, 8).Span, IfNotFrozen(value));");
            Emit("        }");
            Emit("    }");
            Emit("}");
            Emit("namespace T_BaseImplNameSpace_");
            Emit("{");
            Emit("    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>");
            Emit("    {");
            Emit("        private const int T_EntityId_ = 2;");
            Emit("        public new static T_BaseImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)");
            Emit("        {");
            Emit("            SourceBlocks blocks = SourceBlocks.ParseFrom(buffers);");
            Emit("            return blocks.Header.EntityId switch");
            Emit("            {");
            foreach (var derived in entity.DerivedEntities)
            {
                using var _ = NewScope(derived);
                Emit("                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(blocks),");
            }
            Emit("                _ => new T_BaseImplNameSpace_.T_BaseImplName_(blocks)");
            Emit("            };");
            Emit("        }");
            Emit("");
            Emit("        private const int ClassHeight = 1;");
            Emit("        private const int BlockLength = 4; // structure code = 0x0031L;");
            Emit("        private readonly Memory<byte> _writableLocalBlock;");
            Emit("        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;");
            Emit("");
            Emit("        protected override int OnGetEntityId() => 1;");
            Emit("        protected override int OnGetClassHeight() => ClassHeight;");
            Emit("        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);");
            Emit("        protected override void OnFreeze()");
            Emit("        {");
            Emit("            base.OnFreeze();");
            Emit("        }");
            Emit("");
            Emit("        protected override ValueTask OnPack(IDataStore dataStore)");
            Emit("        {");
            Emit("            return base.OnPack(dataStore);");
            Emit("        }");
            Emit("");
            Emit("        protected override ValueTask OnUnpack(IDataStore dataStore, int depth)");
            Emit("        {");
            Emit("            return base.OnUnpack(dataStore, depth);");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(BlockHeader header) : base(header)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(BlockHeader header, T_BaseImplName_ source) : base(header, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("            this.BaseField1 = source.BaseField1;");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(BlockHeader header, T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(header, source)");
            Emit("        {");
            Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
            Emit("            this.BaseField1 = source.BaseField1;");
            Emit("        }");
            Emit("");
            Emit("        protected T_BaseImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(header, sourceBlocks)");
            Emit("        {");
            Emit("            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];");
            Emit("            if (sourceBlock.Length < BlockLength)");
            Emit("            {");
            Emit("                // source too small - allocate new");
            Emit("                Memory<byte> memory = new byte[BlockLength];");
            Emit("                sourceBlock.CopyTo(memory);");
            Emit("                _readonlyLocalBlock = memory;");
            Emit("            }");
            Emit("            else");
            Emit("            {");
            Emit("                _readonlyLocalBlock = sourceBlock;");
            Emit("            }");
            Emit("            _writableLocalBlock = Memory<byte>.Empty;");
            Emit("        }");
            Emit("");
            Emit("        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0001;");
            Emit("        private const long BlockStructureCode = T_BlockStructureCode_;");
            Emit("        private static readonly BlockHeader _header = BlockHeader.CreateNew(T_EntityId_, BlockStructureCode);");
            Emit("        internal T_BaseImplName_(SourceBlocks sourceBlocks) : this(_header, sourceBlocks) { }");
            Emit("");
            Emit("        private const int T_FieldOffset_ = 0;");
            Emit("        private const int T_FieldLength_ = 4;");
            Emit("");
            Emit("        public T_NativeMemberType_ BaseField1");
            Emit("        {");
            Emit("            get => (T_NativeMemberType_)Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span);");
            Emit("            set => Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));");
            Emit("        }");
            Emit("");
            Emit("        public bool Equals(T_BaseImplName_? other)");
            Emit("        {");
            Emit("            if (ReferenceEquals(this, other)) return true;");
            Emit("            if (other is null) return false;");
            Emit("            if (!base.Equals(other)) return false;");
            Emit("            if (!_readonlyLocalBlock.Span.SequenceEqual(other._readonlyLocalBlock.Span)) return false;");
            Emit("            return true;");
            Emit("        }");
            Emit("        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);");
            Emit("        public override int GetHashCode() => base.GetHashCode();");
            Emit("    }");
            Emit("}");
        }
        Emit("namespace T_ImplNameSpace_");
        Emit("{");
        Emit("    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>, IMemBlocksEntity<T_EntityImplName_>");
        Emit("    {");
        Emit("        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_EntityImplName_>");
        Emit("        {");
        Emit("            public T_EntityImplName_ CreateInstance(ReadOnlySequence<byte> buffers) => T_EntityImplName_.DeserializeFrom(buffers);");
        Emit("        }");
        Emit("        private static readonly _EntityFactory _factory = new _EntityFactory();");
        Emit("        public IMemBlocksEntityFactory<T_EntityImplName_> GetFactory() => _factory;");
        Emit("        public static T_EntityImplName_ CreateInstance(ReadOnlySequence<byte> buffers) => T_EntityImplName_.DeserializeFrom(buffers);");
        Emit("");
        if (false)
        {
            Emit("        private const int T_ClassHeight_ = 2;");
            Emit("        private const int T_EntityId_ = 2;");
            Emit("        private const int T_BlockLength_ = 1024;");
            Emit("        private const bool T_MemberObsoleteIsError_ = false;");
            Emit("        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0002;");
        }
        Emit("        private const long BlockStructureCode = T_BlockStructureCode_;");
        Emit("        private const int ClassHeight = T_ClassHeight_;");
        Emit("        private const int BlockLength = T_BlockLength_;");
        Emit("        private readonly Memory<byte> _writableLocalBlock;");
        Emit("        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;");
        Emit("");
        Emit("        private static readonly BlockHeader _header = BlockHeader.CreateNew(T_EntityId_, BlockStructureCode);");
        Emit("");
        Emit("        public new static T_EntityImplName_ CreateRequired(T_EntityImplName_ source)");
        Emit("        {");
        Emit("            if (source.IsFrozen) return source;");
        Emit("            return source switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
        {
            using var _ = NewScope(derived);
            Emit("                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(source)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        public new static T_EntityImplName_? CreateNullable(T_EntityImplName_? source)");
        Emit("        {");
        Emit("            return (source is null) ? null : CreateRequired(source);");
        Emit("        }");
        Emit("");
        Emit("        public new static T_EntityImplName_ CreateRequired(T_IntfNameSpace_.T_EntityIntfName_ source)");
        Emit("        {");
        Emit("            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;");
        Emit("            return source switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight))
        {
            using var _ = NewScope(derived);
            Emit("                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(source)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        public new static T_EntityImplName_? CreateNullable(T_IntfNameSpace_.T_EntityIntfName_? source)");
        Emit("        {");
        Emit("            return (source is null) ? null : CreateRequired(source);");
        Emit("        }");
        Emit("");
        Emit("        public new static T_EntityImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)");
        Emit("        {");
        Emit("            SourceBlocks blocks = SourceBlocks.ParseFrom(buffers);");
        Emit("            return blocks.Header.EntityId switch");
        Emit("            {");
        foreach (var derived in entity.DerivedEntities)
        {
            using var _ = NewScope(derived);
            Emit("                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(blocks),");
        }
        Emit("                _ => new T_ImplNameSpace_.T_EntityImplName_(blocks)");
        Emit("            };");
        Emit("        }");
        Emit("");
        Emit("        protected override int OnGetEntityId() => T_EntityId_;");
        Emit("        protected override int OnGetClassHeight() => ClassHeight;");
        Emit("        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);");
        Emit("        protected override IEntityBase OnPartCopy() => new T_EntityImplName_(this);");
        Emit("");
        Emit("        protected override void OnFreeze()");
        Emit("        {");
        Emit("            base.OnFreeze();");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_?.Freeze();");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_?.Freeze();");
                    }
                    break;
                case MemberKind.Binary:
                    break;
                case MemberKind.String:
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        protected override async ValueTask OnPack(IDataStore dataStore)");
        Emit("        {");
        Emit("            await base.OnPack(dataStore);");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableEntityMemberName__Pack(dataStore);");
                    }
                    else
                    {
                        Emit("            await T_RequiredEntityMemberName__Pack(dataStore);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableBinaryMemberName__Pack(dataStore);");
                    }
                    else
                    {
                        Emit("            await T_RequiredBinaryMemberName__Pack(dataStore);");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableStringMemberName__Pack(dataStore);");
                    }
                    else
                    {
                        Emit("            await T_RequiredStringMemberName__Pack(dataStore);");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        protected override async ValueTask OnUnpack(IDataStore dataStore, int depth)");
        Emit("        {");
        Emit("            await base.OnUnpack(dataStore, depth);");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableEntityMemberName__Unpack(dataStore, depth);");
                    }
                    else
                    {
                        Emit("            await T_RequiredEntityMemberName__Unpack(dataStore, depth);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableBinaryMemberName__Unpack(dataStore);");
                    }
                    else
                    {
                        Emit("            await T_RequiredBinaryMemberName__Unpack(dataStore);");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            await T_NullableStringMemberName__Unpack(dataStore);");
                    }
                    else
                    {
                        Emit("            await T_RequiredStringMemberName__Unpack(dataStore);");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("");
        Emit("        // -------------------- field map -----------------------------");
        Emit("        //  Seq.  Off.  Len.  End.  Type    Name");
        Emit("        //  ----  ----  ----  ----  ------- -------");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            Emit("        //  T_MemberSequenceR4_  T_FieldOffsetR4_  T_FieldLengthR4_  T_MemberBELE_    T_MemberTypeL7_ T_MemberName_");
            if (member.NullAddress is not null)
            {
                Emit("        //        T_BitsFieldOffsetR4_  T_NullBitPositionR4_                T_MemberName_ (isNull bit)");
            }
        }
        Emit("        // ------------------------------------------------------------");
        Emit("");
        Emit("        protected T_EntityImplName_(BlockHeader header) : base(header)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
        Emit("        }");
        Emit("        public T_EntityImplName_() : base(_header)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
        Emit("        }");
        Emit("");
        Emit("        protected T_EntityImplName_(BlockHeader header, T_EntityImplName_ source) : base(header, source)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("        public T_EntityImplName_(T_EntityImplName_ source) : this(_header, source) { }");
        Emit("");
        Emit("        protected T_EntityImplName_(BlockHeader header, T_IntfNameSpace_.T_EntityIntfName_ source) : base(header, source)");
        Emit("        {");
        Emit("            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            Emit("            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;");
                        }
                        else
                        {
                            Emit("            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(source.T_NullableEntityMemberName_);");
                    }
                    else
                    {
                        Emit("            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(source.T_RequiredEntityMemberName_);");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;");
                    }
                    else
                    {
                        Emit("            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
        }
        Emit("        }");
        Emit("        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : this(_header, source) { }");
        Emit("");
        Emit("        protected T_EntityImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(header, sourceBlocks)");
        Emit("        {");
        Emit("            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];");
        Emit("            if (sourceBlock.Length < BlockLength)");
        Emit("            {");
        Emit("                // source too small - allocate new");
        Emit("                _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];");
        Emit("                sourceBlock.CopyTo(_writableLocalBlock);");
        Emit("            }");
        Emit("            else");
        Emit("            {");
        Emit("                _readonlyLocalBlock = sourceBlock;");
        Emit("                _writableLocalBlock = Memory<byte>.Empty;");
        Emit("            }");
        Emit("        }");
        Emit("        internal T_EntityImplName_(SourceBlocks sourceBlocks) : this(_header, sourceBlocks) { }");
        Emit("        public T_EntityImplName_(ReadOnlySequence<byte> buffers) : this(_header, SourceBlocks.ParseFrom(buffers)) { }");
        Emit("");
        if (false)
        {
            Emit("        private const int T_RequiredNativeStructFieldOffset_ = 0;");
            Emit("        private const int T_RequiredCustomStructFieldOffset_ = 4;");
            Emit("        private const int T_NullableCustomStructFieldOffset_ = 8;");
            Emit("        private const int T_NullableNativeStructFieldOffset_ = 12;");
            Emit("");
            Emit("        private const int T_NullableEntityFieldOffset_ = 64;");
            Emit("        private const int T_RequiredEntityFieldOffset_ = 128;");
            Emit("");
            Emit("        private const int T_NullableBinaryFieldOffset_ = 256;");
            Emit("        private const int T_RequiredBinaryFieldOffset_ = 320;");
            Emit("");
            Emit("        private const int T_NullableStringFieldOffset_ = 448;");
            Emit("        private const int T_RequiredStringFieldOffset_ = 512;");
            Emit("");
            Emit("        private const int T_FieldLength_ = 4;");
            Emit("        private const bool T_IsBigEndian_ = false;");
            Emit("        private const int T_BitsFieldOffset_ = 0;");
            Emit("        private const int T_BitsFieldLength_ = 4;");
            Emit("        private const int T_NullBitPosition_ = 0;");
        }
        foreach (var member in entity.Members)
        {
            using var _ = NewScope(entity, member);
            switch (member.Kind)
            {
                case MemberKind.Struct:
                    if (member.IsNullable)
                    {
                        if (member.IsCustom)
                        {
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_CustomMemberType_? T_NullableCustomStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                var bits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                if (bits.GetBit(T_NullBitPosition_)) return null;");
                            Emit("                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                Bits32 oldBits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                Bits32 newBits = oldBits.SetBit(T_NullBitPosition_, !value.HasValue);");
                            Emit("                if (newBits != oldBits)");
                            Emit("                {");
                            Emit("                    Codec_UInt32_LE.WriteToSpan(_writableLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span, newBits.Data);");
                            Emit("                }");
                            Emit("                if (value.HasValue)");
                            Emit("                {");
                            Emit("                    T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value.Value);");
                            Emit("                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);");
                            Emit("                }");
                            Emit("                else");
                            Emit("                {");
                            Emit("                    _writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span.Clear();");
                            Emit("                }");
                            Emit("            }");
                            Emit("        }");
                        }
                        else
                        {
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_NativeMemberType_? T_NullableNativeStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                var bits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                if (bits.GetBit(T_NullBitPosition_)) return null;");
                            Emit("                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                Bits32 oldBits = new Bits32(Codec_UInt32_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span));");
                            Emit("                Bits32 newBits = oldBits.SetBit(T_NullBitPosition_, !value.HasValue);");
                            Emit("                if (newBits != oldBits)");
                            Emit("                {");
                            Emit("                    Codec_UInt32_LE.WriteToSpan(_writableLocalBlock.Slice(T_BitsFieldOffset_, T_BitsFieldLength_).Span, newBits.Data);");
                            Emit("                }");
                            Emit("                if (value.HasValue)");
                            Emit("                {");
                            Emit("                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span, value.Value);");
                            Emit("                }");
                            Emit("                else");
                            Emit("                {");
                            Emit("                    _writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span.Clear();");
                            Emit("                }");
                            Emit("            }");
                            Emit("        }");
                        }
                    }
                    else
                    {
                        if (member.IsCustom)
                        {
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_CustomMemberType_ T_RequiredCustomStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value);");
                            Emit("                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);");
                            Emit("            }");
                            Emit("        }");
                        }
                        else
                        {
                            if (member.IsObsolete)
                            {
                                Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                            }
                            Emit("        public T_NativeMemberType_ T_RequiredNativeStructMemberName_");
                            Emit("        {");
                            Emit("            get");
                            Emit("            {");
                            Emit("                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span);");
                            Emit("            }");
                            Emit("            set");
                            Emit("            {");
                            Emit("                ThrowIfFrozen();");
                            Emit("                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span, value);");
                            Emit("            }");
                            Emit("        }");
                        }
                    }
                    break;
                case MemberKind.Entity:
                    if (member.IsNullable)
                    {
                        Emit("        private async ValueTask T_NullableEntityMemberName__Pack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = default;");
                        Emit("            if (_T_NullableEntityMemberName_ is not null)");
                        Emit("            {");
                        Emit("                await _T_NullableEntityMemberName_.Pack(dataStore);");
                        Emit("                var buffers = _T_NullableEntityMemberName_.GetBuffers();");
                        Emit("                blobId = await dataStore.PutBlob(buffers);");
                        Emit("            }");
                        Emit("            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span);");
                        Emit("        }");
                        Emit("        private async ValueTask T_NullableEntityMemberName__Unpack(IDataStore dataStore, int depth)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span);");
                        Emit("            var blob = await dataStore.GetBlob(blobId);");
                        Emit("            _T_NullableEntityMemberName_ = null;");
                        Emit("            if (blob is not null)");
                        Emit("            {");
                        Emit("                _T_NullableEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(blob.Value);");
                        Emit("                await _T_NullableEntityMemberName_.Unpack(dataStore, depth - 1);");
                        Emit("            }");
                        Emit("        }");
                        Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableEntityMemberName_);");
                        Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                        Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableEntityMemberName_);");
                        Emit("            set => _T_NullableEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(value));");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        private async ValueTask T_RequiredEntityMemberName__Pack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            if (_T_RequiredEntityMemberName_ is null)");
                        Emit("            {");
                        Emit("                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore);");
                        Emit("            }");
                        Emit("            await _T_RequiredEntityMemberName_.Pack(dataStore);");
                        Emit("            var buffers = _T_RequiredEntityMemberName_.GetBuffers();");
                        Emit("            BlobIdV1 blobId = await dataStore.PutBlob(buffers);");
                        Emit("            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span);");
                        Emit("        }");
                        Emit("        private async ValueTask T_RequiredEntityMemberName__Unpack(IDataStore dataStore, int depth)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span);");
                        Emit("            var blob = await dataStore.GetBlob(blobId);");
                        Emit("            if (blob is null)");
                        Emit("            {");
                        Emit("                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore);");
                        Emit("            }");
                        Emit("            else");
                        Emit("            {");
                        Emit("                _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(blob.Value);");
                        Emit("                await _T_RequiredEntityMemberName_.Unpack(dataStore, depth - 1);");
                        Emit("            }");
                        Emit("        }");
                        Emit("        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_RequiredEntityMemberName_ = null;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));");
                        Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                        Emit("        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_");
                        Emit("        {");
                        Emit("            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));");
                        Emit("            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(value));");
                        Emit("        }");
                    }
                    break;
                case MemberKind.Binary:
                    if (member.IsNullable)
                    {
                        Emit("        private async ValueTask T_NullableBinaryMemberName__Pack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = _T_NullableBinaryMemberName_ is null");
                        Emit("                ? default");
                        Emit("                : await dataStore.PutBlob(_T_NullableBinaryMemberName_.Sequence);");
                        Emit("            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64).Span);");
                        Emit("        }");
                        Emit("        private async ValueTask T_NullableBinaryMemberName__Unpack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64).Span);");
                        Emit("            var blob = await dataStore.GetBlob(blobId);");
                        Emit("            _T_NullableBinaryMemberName_ = blob is null ? null : Octets.UnsafeWrap(blob.Value);");
                        Emit("        }");
                        Emit("        private Octets? _T_NullableBinaryMemberName_;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public Octets? T_NullableBinaryMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableBinaryMemberName_);");
                        Emit("            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        private async ValueTask T_RequiredBinaryMemberName__Pack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            var buffers = _T_RequiredBinaryMemberName_.Sequence;");
                        Emit("            BlobIdV1 blobId = await dataStore.PutBlob(buffers);");
                        Emit("            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64).Span);");
                        Emit("        }");
                        Emit("        private async ValueTask T_RequiredBinaryMemberName__Unpack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64).Span);");
                        Emit("            var blob = await dataStore.GetBlob(blobId);");
                        Emit("            _T_RequiredBinaryMemberName_ = blob is null ? Octets.Empty : Octets.UnsafeWrap(blob.Value);");
                        Emit("");
                        Emit("        }");
                        Emit("        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public Octets T_RequiredBinaryMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_RequiredBinaryMemberName_);");
                        Emit("            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    break;
                case MemberKind.String:
                    if (member.IsNullable)
                    {
                        Emit("        private async ValueTask T_NullableStringMemberName__Pack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = _T_NullableStringMemberName_ is null");
                        Emit("                ? default");
                        Emit("                : blobId = await dataStore.PutBlob(new ReadOnlySequence<byte>(System.Text.Encoding.UTF8.GetBytes(_T_NullableStringMemberName_)));");
                        Emit("            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableStringFieldOffset_, 64).Span);");
                        Emit("        }");
                        Emit("        private async ValueTask T_NullableStringMemberName__Unpack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_NullableStringFieldOffset_, 64).Span);");
                        Emit("            var blob = await dataStore.GetBlob(blobId);");
                        Emit("#if NET8_0_OR_GREATER");
                        Emit("            _T_NullableStringMemberName_ = blob is null ? null : System.Text.Encoding.UTF8.GetString(blob.Value);");
                        Emit("#else");
                        Emit("            _T_NullableStringMemberName_ = blob is null ? null : System.Text.Encoding.UTF8.GetString(blob.Value.ToArray());");
                        Emit("#endif");
                        Emit("        }");
                        Emit("        private string? _T_NullableStringMemberName_;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public string? T_NullableStringMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_NullableStringMemberName_);");
                        Emit("            set => _T_NullableStringMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    else
                    {
                        Emit("        private async ValueTask T_RequiredStringMemberName__Pack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = default;");
                        Emit("            var buffers = new ReadOnlySequence<byte>(System.Text.Encoding.UTF8.GetBytes(_T_RequiredStringMemberName_));");
                        Emit("            blobId = await dataStore.PutBlob(buffers);");
                        Emit("            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredStringFieldOffset_, 64).Span);");
                        Emit("        }");
                        Emit("        private async ValueTask T_RequiredStringMemberName__Unpack(IDataStore dataStore)");
                        Emit("        {");
                        Emit("            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_RequiredStringFieldOffset_, 64).Span);");
                        Emit("            var blob = await dataStore.GetBlob(blobId);");
                        Emit("#if NET8_0_OR_GREATER");
                        Emit("            _T_RequiredStringMemberName_ = blob is null ? string.Empty : System.Text.Encoding.UTF8.GetString(blob.Value);");
                        Emit("#else");
                        Emit("            _T_RequiredStringMemberName_ = blob is null ? string.Empty : System.Text.Encoding.UTF8.GetString(blob.Value.ToArray());");
                        Emit("#endif");
                        Emit("        }");
                        Emit("        private string _T_RequiredStringMemberName_ = string.Empty;");
                        if (member.IsObsolete)
                        {
                            Emit("        [Obsolete(\"T_MemberObsoleteMessage_\", T_MemberObsoleteIsError_)]");
                        }
                        Emit("        public string T_RequiredStringMemberName_");
                        Emit("        {");
                        Emit("            get => IfUnpacked(_T_RequiredStringMemberName_);");
                        Emit("            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);");
                        Emit("        }");
                    }
                    break;
                default:
                    Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
                    break;
            } // switch
            Emit("");
        }
        Emit("");
        Emit("        public bool Equals(T_EntityImplName_? other)");
        Emit("        {");
        Emit("            if (ReferenceEquals(this, other)) return true;");
        Emit("            if (other is null) return false;");
        Emit("            if (!base.Equals(other)) return false;");
        Emit("            if (!_readonlyLocalBlock.Span.SequenceEqual(other._readonlyLocalBlock.Span)) return false;");
        Emit("            return true;");
        Emit("        }");
        Emit("        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);");
        Emit("        public override int GetHashCode() => base.GetHashCode();");
        Emit("        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);");
        Emit("        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);");
        Emit("");
        Emit("    }");
        Emit("}");
    }
}
