//##using System;
//##using System.Linq;
//##using DTOMaker.SrcGen.Core;
//##namespace DTOMaker.SrcGen.MemBlocks;
//###pragma warning disable CS0162 // Unreachable code detected
//##public sealed class EntityGenerator : EntityGeneratorBase
//##{
//##    public EntityGenerator(SourceGeneratorParameters parameters) : base(parameters) { }
//##    protected override void OnGenerate(OutputEntity entity)
//##    {
//##        using var entityScope = NewScope(entity);
// <auto-generated>
// Warning: This file was generated by a source generator.
// Changes made to this file will be lost if re-generated.
// </auto-generated>
//##if(false) {
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0162 // Unreachable code detected
//##}
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using DataFac.Memory;
using DTOMaker.Runtime;
using DTOMaker.Runtime.MemBlocks;
using DataFac.Storage;
using System;
using System.Buffers;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using T_ImplNameSpace_;
//##if(false) {
using T_MemberType_ = System.Int32;
namespace DataFac.Memory
{
    public static class Codec_T_MemberType__T_MemberBELE_
    {
        public static T_MemberType_ ReadFromSpan(ReadOnlySpan<byte> source) => Codec_Int32_LE.ReadFromSpan(source);
        public static void WriteToSpan(Span<byte> source, T_MemberType_ value) => Codec_Int32_LE.WriteToSpan(source, value);
    }
}
namespace T_MemberTypeIntfSpace_
{
    public interface T_MemberTypeIntfName_
    {
        Int64 Field1 { get; set; }
    }
}
namespace T_MemberTypeImplSpace_
{
    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_
    {
        private const int ClassHeight = 1;
        private const int BlockLength = 8;
        private const long StructureCode = 0x00_41L;
        private static readonly BlockHeader _header = BlockHeader.CreateNew(3, StructureCode);

        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeImplName_ source)
        {
            if (source.IsFrozen) return source;
            return new T_MemberTypeImplName_(source);
        }
        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeImplName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }
        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)
        {
            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;
            return new T_MemberTypeImplName_(source);
        }
        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }
        public static T_MemberTypeImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)
        {
            return new T_MemberTypeImplName_(buffers);
        }
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;
        public T_MemberTypeImplName_() : base(_header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }
        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }
        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            this.Field1 = source.Field1;
        }
        protected T_MemberTypeImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(_header, sourceBlocks)
        {
            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];
            if (sourceBlock.Length < BlockLength)
            {
                // source too small - allocate new
                _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
                sourceBlock.CopyTo(_writableLocalBlock);
            }
            else
            {
                _readonlyLocalBlock = sourceBlock;
                _writableLocalBlock = Memory<byte>.Empty;
            }
        }
        public T_MemberTypeImplName_(ReadOnlySequence<byte> buffers) : this(_header, SourceBlocks.ParseFrom(buffers)) { }

        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);
        protected override IEntityBase OnPartCopy() => throw new NotImplementedException();
        protected override int OnGetEntityId() => 3;
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ValueTask OnPack(IDataStore dataStore) => default;
        protected override ValueTask OnUnpack(IDataStore dataStore, int depth) => default;

        public Int64 Field1
        {
            get => Codec_Int64_LE.ReadFromSpan(_readonlyLocalBlock.Slice(0, 8).Span);
            set => Codec_Int64_LE.WriteToSpan(_writableLocalBlock.Slice(0, 8).Span, IfNotFrozen(value));
        }
    }
}
namespace T_BaseIntfNameSpace_
{
    public interface T_BaseIntfName_ : IEntityBase
    {
        T_MemberType_ BaseField1 { get; set; }
    }
}
namespace T_BaseImplNameSpace_
{
    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>
    {
        private const int T_EntityId_ = 2;
        public new static T_BaseImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)
        {
            SourceBlocks blocks = SourceBlocks.ParseFrom(buffers);
            return blocks.Header.EntityId switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(blocks),
                //##}
                _ => new T_BaseImplNameSpace_.T_BaseImplName_(blocks)
            };
        }

        private const int ClassHeight = 1;
        private const int BlockLength = 4; // structure code = 0x0031L;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        protected override int OnGetEntityId() => 1;
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);
        protected override void OnFreeze()
        {
            base.OnFreeze();
        }

        protected override ValueTask OnPack(IDataStore dataStore)
        {
            return base.OnPack(dataStore);
        }

        protected override ValueTask OnUnpack(IDataStore dataStore, int depth)
        {
            return base.OnUnpack(dataStore, depth);
        }

        protected T_BaseImplName_(BlockHeader header) : base(header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }

        protected T_BaseImplName_(BlockHeader header, T_BaseImplName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseImplName_(BlockHeader header, T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(header, sourceBlocks)
        {
            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];
            if (sourceBlock.Length < BlockLength)
            {
                // source too small - allocate new
                Memory<byte> memory = new byte[BlockLength];
                sourceBlock.CopyTo(memory);
                _readonlyLocalBlock = memory;
            }
            else
            {
                _readonlyLocalBlock = sourceBlock;
            }
            _writableLocalBlock = Memory<byte>.Empty;
        }

        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0001;
        private const long BlockStructureCode = T_BlockStructureCode_;
        private static readonly BlockHeader _header = BlockHeader.CreateNew(T_EntityId_, BlockStructureCode);
        internal T_BaseImplName_(SourceBlocks sourceBlocks) : this(_header, sourceBlocks) { }

        private const int T_FieldOffset_ = 0;
        private const int T_FieldLength_ = 4;

        public T_MemberType_ BaseField1
        {
            get => (T_MemberType_)Codec_T_MemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span);
            set => Codec_T_MemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));
        }

        public bool Equals(T_BaseImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            if (!_readonlyLocalBlock.Span.SequenceEqual(other._readonlyLocalBlock.Span)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
    }
}
namespace T_IntfNameSpace_
{
    public interface T_EntityIntfName_ : T_BaseIntfNameSpace_.T_BaseIntfName_
    {
        //T_MemberType_? T_NullableScalarMemberName_ { get; set; }
        T_MemberType_ T_RequiredScalarMemberName_ { get; set; }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_NullableEntityMemberName_ { get; set; }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_RequiredEntityMemberName_ { get; set; }
        Octets? T_NullableFixLenBinaryMemberName_ { get; set; }
        Octets? T_NullableVarLenBinaryMemberName_ { get; set; }
        Octets T_RequiredFixLenBinaryMemberName_ { get; set; }
        Octets T_RequiredVarLenBinaryMemberName_ { get; set; }
        String? T_NullableFixLenStringMemberName_ { get; set; }
        String? T_NullableVarLenStringMemberName_ { get; set; }
        String T_RequiredFixLenStringMemberName_ { get; set; }
        String T_RequiredVarLenStringMemberName_ { get; set; }
    }
}
//##}
namespace T_ImplNameSpace_
{
    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>, IMemBlocksEntity<T_EntityImplName_>
    {
        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_EntityImplName_>
        {
            public T_EntityImplName_ CreateInstance(ReadOnlySequence<byte> buffers) => T_EntityImplName_.DeserializeFrom(buffers);
        }
        private static readonly _EntityFactory _factory = new _EntityFactory();
        public IMemBlocksEntityFactory<T_EntityImplName_> GetFactory() => _factory;
        public static T_EntityImplName_ CreateInstance(ReadOnlySequence<byte> buffers) => T_EntityImplName_.DeserializeFrom(buffers);

        //##if(false) {
        private const int T_ClassHeight_ = 2;
        private const int T_EntityId_ = 2;
        private const int T_BlockLength_ = 1024;
        private const bool T_MemberObsoleteIsError_ = false;
        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0002;
        //##}
        private const long BlockStructureCode = T_BlockStructureCode_;
        private const int ClassHeight = T_ClassHeight_;
        private const int BlockLength = T_BlockLength_;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        private static readonly BlockHeader _header = BlockHeader.CreateNew(T_EntityId_, BlockStructureCode);

        public new static T_EntityImplName_ CreateRequired(T_EntityImplName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        public new static T_EntityImplName_? CreateNullable(T_EntityImplName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }

        public new static T_EntityImplName_ CreateRequired(T_IntfNameSpace_.T_EntityIntfName_ source)
        {
            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        public new static T_EntityImplName_? CreateNullable(T_IntfNameSpace_.T_EntityIntfName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }

        public new static T_EntityImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)
        {
            SourceBlocks blocks = SourceBlocks.ParseFrom(buffers);
            return blocks.Header.EntityId switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(blocks),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(blocks)
            };
        }

        protected override int OnGetEntityId() => T_EntityId_;
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);
        protected override IEntityBase OnPartCopy() => new T_EntityImplName_(this);

        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Native:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_?.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##case MemberKind.String:
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override async ValueTask OnPack(IDataStore dataStore)
        {
            await base.OnPack(dataStore);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Native:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Pack(dataStore);
            //##} else {
            await T_RequiredEntityMemberName__Pack(dataStore);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            T_NullableFixLenBinaryMemberName__Pack();
            //##} else {
            await T_NullableVarLenBinaryMemberName__Pack(dataStore);
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            T_RequiredFixLenBinaryMemberName__Pack();
            //##} else {
            await T_RequiredVarLenBinaryMemberName__Pack(dataStore);
            //##}
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            T_NullableFixLenStringMemberName__Pack();
            //##} else {
            await T_NullableVarLenStringMemberName__Pack(dataStore);
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            T_RequiredFixLenStringMemberName__Pack();
            //##} else {
            await T_RequiredVarLenStringMemberName__Pack(dataStore);
            //##}
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override async ValueTask OnUnpack(IDataStore dataStore, int depth)
        {
            await base.OnUnpack(dataStore, depth);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Native:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Unpack(dataStore, depth);
            //##} else {
            await T_RequiredEntityMemberName__Unpack(dataStore, depth);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            T_NullableFixLenBinaryMemberName__Unpack();
            //##} else {
            await T_NullableVarLenBinaryMemberName__Unpack(dataStore);
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            T_RequiredFixLenBinaryMemberName__Unpack();
            //##} else {
            await T_RequiredVarLenBinaryMemberName__Unpack(dataStore);
            //##}
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            T_NullableFixLenStringMemberName__Unpack();
            //##} else {
            await T_NullableVarLenStringMemberName__Unpack(dataStore);
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            T_RequiredFixLenStringMemberName__Unpack();
            //##} else {
            await T_RequiredVarLenStringMemberName__Unpack(dataStore);
            //##}
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        // -------------------- field map -----------------------------
        //  Seq.  Off.  Len.  End.  Type    Name
        //  ----  ----  ----  ----  ------- -------
        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //  T_MemberSequenceR4_  T_FieldOffsetR4_  T_FieldLengthR4_  T_MemberBELE_    T_MemberTypeL7_ T_MemberName_
        //##}
        // ------------------------------------------------------------

        protected T_EntityImplName_(BlockHeader header) : base(header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }
        public T_EntityImplName_() : base(_header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }

        protected T_EntityImplName_(BlockHeader header, T_EntityImplName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Native:
            this.T_RequiredScalarMemberName_ = source.T_RequiredScalarMemberName_;
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;
            //##} else {
            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            _T_NullableFixLenBinaryMemberName_ = source._T_NullableFixLenBinaryMemberName_;
            //##} else {
            _T_NullableVarLenBinaryMemberName_ = source._T_NullableVarLenBinaryMemberName_;
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            _T_RequiredFixLenBinaryMemberName_ = source._T_RequiredFixLenBinaryMemberName_;
            //##} else {
            _T_RequiredVarLenBinaryMemberName_ = source._T_RequiredVarLenBinaryMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            _T_NullableFixLenStringMemberName_ = source._T_NullableFixLenStringMemberName_;
            //##} else {
            _T_NullableVarLenStringMemberName_ = source._T_NullableVarLenStringMemberName_;
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            _T_RequiredFixLenStringMemberName_ = source._T_RequiredFixLenStringMemberName_;
            //##} else {
            _T_RequiredVarLenStringMemberName_ = source._T_RequiredVarLenStringMemberName_;
            //##}
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }
        public T_EntityImplName_(T_EntityImplName_ source) : this(_header, source) { }

        protected T_EntityImplName_(BlockHeader header, T_IntfNameSpace_.T_EntityIntfName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Native:
            this.T_RequiredScalarMemberName_ = source.T_RequiredScalarMemberName_;
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            _T_NullableFixLenBinaryMemberName_ = source.T_NullableFixLenBinaryMemberName_;
            //##} else {
            _T_NullableVarLenBinaryMemberName_ = source.T_NullableVarLenBinaryMemberName_;
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            _T_RequiredFixLenBinaryMemberName_ = source.T_RequiredFixLenBinaryMemberName_;
            //##} else {
            _T_RequiredVarLenBinaryMemberName_ = source.T_RequiredVarLenBinaryMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            //##if (member.IsEmbedded) {
            _T_NullableFixLenStringMemberName_ = source.T_NullableFixLenStringMemberName_;
            //##} else {
            _T_NullableVarLenStringMemberName_ = source.T_NullableVarLenStringMemberName_;
            //##}
            //##} else {
            //##if (member.IsEmbedded) {
            _T_RequiredFixLenStringMemberName_ = source.T_RequiredFixLenStringMemberName_;
            //##} else {
            _T_RequiredVarLenStringMemberName_ = source.T_RequiredVarLenStringMemberName_;
            //##}
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }
        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : this(_header, source) { }

        protected T_EntityImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(header, sourceBlocks)
        {
            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];
            if (sourceBlock.Length < BlockLength)
            {
                // source too small - allocate new
                _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
                sourceBlock.CopyTo(_writableLocalBlock);
            }
            else
            {
                _readonlyLocalBlock = sourceBlock;
                _writableLocalBlock = Memory<byte>.Empty;
            }
        }
        internal T_EntityImplName_(SourceBlocks sourceBlocks) : this(_header, sourceBlocks) { }
        public T_EntityImplName_(ReadOnlySequence<byte> buffers) : this(_header, SourceBlocks.ParseFrom(buffers)) { }

        //##if(false) {
        private const int T_RequiredScalarFieldOffset_ = 0;
        private const int T_NullableEntityFieldOffset_ = 64;
        private const int T_RequiredEntityFieldOffset_ = 128;
        private const int T_NullableFixLenBinaryFieldOffset_ = 192;
        private const int T_NullableFixLenBinaryFieldLength_ = 32;
        private const int T_RequiredFixLenBinaryFieldOffset_ = 224;
        private const int T_RequiredFixLenBinaryFieldLength_ = 32;

        private const int T_NullableVarLenBinaryFieldOffset_ = 256;
        private const int T_RequiredVarLenBinaryFieldOffset_ = 320;

        private const int T_NullableFixLenStringFieldOffset_ = 384;
        private const int T_NullableFixLenStringFieldLength_ = 32;
        private const int T_RequiredFixLenStringFieldOffset_ = 416;
        private const int T_RequiredFixLenStringFieldLength_ = 32;

        private const int T_NullableVarLenStringFieldOffset_ = 448;
        private const int T_RequiredVarLenStringFieldOffset_ = 512;

        private const int T_FieldLength_ = 8;
        private const bool T_IsBigEndian_ = false;
        //##}
        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //##switch(member.Kind) {
        //##case MemberKind.Native:
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberType_ T_RequiredScalarMemberName_
        {
            get => Codec_T_MemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredScalarFieldOffset_, T_FieldLength_).Span);
            set => Codec_T_MemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredScalarFieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));
        }
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableEntityMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            if (_T_NullableEntityMemberName_ is not null)
            {
                await _T_NullableEntityMemberName_.Pack(dataStore);
                var buffers = _T_NullableEntityMemberName_.GetBuffers();
                blobId = await dataStore.PutBlob(buffers);
            }
            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span);
        }
        private async ValueTask T_NullableEntityMemberName__Unpack(IDataStore dataStore, int depth)
        {
            BlobIdV1 blobId = BlobIdV1.UnsafeWrap(_readonlyLocalBlock.Slice(T_NullableEntityFieldOffset_, 64));
            var blob = await dataStore.GetBlob(blobId);
            _T_NullableEntityMemberName_ = null;
            if (blob is not null)
            {
                _T_NullableEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(blob.Value);
                await _T_NullableEntityMemberName_.Unpack(dataStore, depth - 1);
            }
        }
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(value));
        }
        //##} else {
        private async ValueTask T_RequiredEntityMemberName__Pack(IDataStore dataStore)
        {
            if (_T_RequiredEntityMemberName_ is null)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore);
            }
            await _T_RequiredEntityMemberName_.Pack(dataStore);
            var buffers = _T_RequiredEntityMemberName_.GetBuffers();
            BlobIdV1 blobId = await dataStore.PutBlob(buffers);
            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span);
        }
        private async ValueTask T_RequiredEntityMemberName__Unpack(IDataStore dataStore, int depth)
        {
            BlobIdV1 blobId = BlobIdV1.UnsafeWrap(_readonlyLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64));
            var blob = await dataStore.GetBlob(blobId);
            if (blob is null)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore);
            }
            else
            {
                _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(blob.Value);
                await _T_RequiredEntityMemberName_.Unpack(dataStore, depth - 1);
            }
        }
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_RequiredEntityMemberName_ = null;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        //##if (member.IsEmbedded) {
        private void T_NullableFixLenBinaryMemberName__Pack()
        {
            Codec_Memory_NE.WriteToSpan(_writableLocalBlock.Slice(T_NullableFixLenBinaryFieldOffset_, T_NullableFixLenBinaryFieldLength_),
                _T_NullableFixLenBinaryMemberName_ is null ? (ReadOnlyMemory<byte>?)null : _T_NullableFixLenBinaryMemberName_.AsMemory());
        }
        private void T_NullableFixLenBinaryMemberName__Unpack()
        {
            ReadOnlyMemory<byte>? memory = Codec_Memory_NE.ReadFromMemory(_readonlyLocalBlock.Slice(T_NullableFixLenBinaryFieldOffset_, T_NullableFixLenBinaryFieldLength_));
            _T_NullableFixLenBinaryMemberName_ = memory is null ? null : Octets.UnsafeWrap(memory.Value);
        }
        private Octets? _T_NullableFixLenBinaryMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets? T_NullableFixLenBinaryMemberName_
        {
            get => IfUnpacked(_T_NullableFixLenBinaryMemberName_);
            set => _T_NullableFixLenBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_NullableVarLenBinaryMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = _T_NullableVarLenBinaryMemberName_ is null
                ? default
                : await dataStore.PutBlob(_T_NullableVarLenBinaryMemberName_.Sequence);
            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableVarLenBinaryFieldOffset_, 64).Span);
        }
        private async ValueTask T_NullableVarLenBinaryMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.UnsafeWrap(_readonlyLocalBlock.Slice(T_NullableVarLenBinaryFieldOffset_, 64));
            var blob = await dataStore.GetBlob(blobId);
            _T_NullableVarLenBinaryMemberName_ = blob is null ? null : Octets.UnsafeWrap(blob.Value);
        }
        private Octets? _T_NullableVarLenBinaryMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets? T_NullableVarLenBinaryMemberName_
        {
            get => IfUnpacked(_T_NullableVarLenBinaryMemberName_);
            set => _T_NullableVarLenBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##} else {
        //##if (member.IsEmbedded) {
        private void T_RequiredFixLenBinaryMemberName__Pack()
        {
            Codec_Memory_NE.WriteToSpan(_writableLocalBlock.Slice(T_RequiredFixLenBinaryFieldOffset_, T_RequiredFixLenBinaryFieldLength_),
                _T_RequiredFixLenBinaryMemberName_.AsMemory());
        }
        private void T_RequiredFixLenBinaryMemberName__Unpack()
        {
            ReadOnlyMemory<byte>? memory = Codec_Memory_NE.ReadFromMemory(_readonlyLocalBlock.Slice(T_RequiredFixLenBinaryFieldOffset_, T_RequiredFixLenBinaryFieldLength_));
            _T_RequiredFixLenBinaryMemberName_ = memory is null ? Octets.Empty : Octets.UnsafeWrap(memory.Value);
        }
        private Octets _T_RequiredFixLenBinaryMemberName_ = Octets.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets T_RequiredFixLenBinaryMemberName_
        {
            get => IfUnpacked(_T_RequiredFixLenBinaryMemberName_);
            set => _T_RequiredFixLenBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredVarLenBinaryMemberName__Pack(IDataStore dataStore)
        {
            var buffers = _T_RequiredVarLenBinaryMemberName_.Sequence;
            BlobIdV1 blobId = await dataStore.PutBlob(buffers);
            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredVarLenBinaryFieldOffset_, 64).Span);
        }
        private async ValueTask T_RequiredVarLenBinaryMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.UnsafeWrap(_readonlyLocalBlock.Slice(T_RequiredVarLenBinaryFieldOffset_, 64));
            var blob = await dataStore.GetBlob(blobId);
            _T_RequiredVarLenBinaryMemberName_ = blob is null ? Octets.Empty : Octets.UnsafeWrap(blob.Value);

        }
        private Octets _T_RequiredVarLenBinaryMemberName_ = Octets.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets T_RequiredVarLenBinaryMemberName_
        {
            get => IfUnpacked(_T_RequiredVarLenBinaryMemberName_);
            set => _T_RequiredVarLenBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        //##if (member.IsEmbedded) {
        private void T_NullableFixLenStringMemberName__Pack()
        {
            Codec_Memory_NE.WriteToSpan(_writableLocalBlock.Slice(T_NullableFixLenStringFieldOffset_, T_NullableFixLenStringFieldLength_),
                _T_NullableFixLenStringMemberName_ is null ? (ReadOnlyMemory<byte>?)null : System.Text.Encoding.UTF8.GetBytes(_T_NullableFixLenStringMemberName_));
        }
        private void T_NullableFixLenStringMemberName__Unpack()
        {
            ReadOnlyMemory<byte>? memory = Codec_Memory_NE.ReadFromMemory(_readonlyLocalBlock.Slice(T_NullableFixLenStringFieldOffset_, T_NullableFixLenStringFieldLength_));
#if NET8_0_OR_GREATER
            _T_NullableFixLenStringMemberName_ = memory is null ? null : System.Text.Encoding.UTF8.GetString(memory.Value.Span);
#else
            _T_NullableFixLenStringMemberName_ = memory is null ? null : System.Text.Encoding.UTF8.GetString(memory.Value.ToArray());
#endif
        }
        private string? _T_NullableFixLenStringMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string? T_NullableFixLenStringMemberName_
        {
            get => IfUnpacked(_T_NullableFixLenStringMemberName_);
            set => _T_NullableFixLenStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_NullableVarLenStringMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = _T_NullableVarLenStringMemberName_ is null
                ? default
                : blobId = await dataStore.PutBlob(new ReadOnlySequence<byte>(System.Text.Encoding.UTF8.GetBytes(_T_NullableVarLenStringMemberName_)));
            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableVarLenStringFieldOffset_, 64).Span);
        }
        private async ValueTask T_NullableVarLenStringMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.UnsafeWrap(_readonlyLocalBlock.Slice(T_NullableVarLenStringFieldOffset_, 64));
            var blob = await dataStore.GetBlob(blobId);
#if NET8_0_OR_GREATER
            _T_NullableVarLenStringMemberName_ = blob is null ? null : System.Text.Encoding.UTF8.GetString(blob.Value);
#else
            _T_NullableVarLenStringMemberName_ = blob is null ? null : System.Text.Encoding.UTF8.GetString(blob.Value.ToArray());
#endif
        }
        private string? _T_NullableVarLenStringMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string? T_NullableVarLenStringMemberName_
        {
            get => IfUnpacked(_T_NullableVarLenStringMemberName_);
            set => _T_NullableVarLenStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##} else {
        //##if (member.IsEmbedded) {
        private void T_RequiredFixLenStringMemberName__Pack()
        {
            Codec_Memory_NE.WriteToSpan(_writableLocalBlock.Slice(T_RequiredFixLenStringFieldOffset_, T_RequiredFixLenStringFieldLength_),
                System.Text.Encoding.UTF8.GetBytes(_T_RequiredFixLenStringMemberName_));
        }
        private void T_RequiredFixLenStringMemberName__Unpack()
        {
            ReadOnlyMemory<byte>? memory = Codec_Memory_NE.ReadFromMemory(_readonlyLocalBlock.Slice(T_RequiredFixLenStringFieldOffset_, T_RequiredFixLenStringFieldLength_));
#if NET8_0_OR_GREATER
            _T_RequiredFixLenStringMemberName_ = memory is null ? string.Empty : System.Text.Encoding.UTF8.GetString(memory.Value.Span);
#else
            _T_RequiredFixLenStringMemberName_ = memory is null ? string.Empty : System.Text.Encoding.UTF8.GetString(memory.Value.ToArray());
#endif
        }
        private string _T_RequiredFixLenStringMemberName_ = string.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string T_RequiredFixLenStringMemberName_
        {
            get => IfUnpacked(_T_RequiredFixLenStringMemberName_);
            set => _T_RequiredFixLenStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredVarLenStringMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            var buffers = new ReadOnlySequence<byte>(System.Text.Encoding.UTF8.GetBytes(_T_RequiredVarLenStringMemberName_));
            blobId = await dataStore.PutBlob(buffers);
            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredVarLenStringFieldOffset_, 64).Span);
        }
        private async ValueTask T_RequiredVarLenStringMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.UnsafeWrap(_readonlyLocalBlock.Slice(T_RequiredVarLenStringFieldOffset_, 64));
            var blob = await dataStore.GetBlob(blobId);
#if NET8_0_OR_GREATER
            _T_RequiredVarLenStringMemberName_ = blob is null ? string.Empty : System.Text.Encoding.UTF8.GetString(blob.Value);
#else
            _T_RequiredVarLenStringMemberName_ = blob is null ? string.Empty : System.Text.Encoding.UTF8.GetString(blob.Value.ToArray());
#endif
        }
        private string _T_RequiredVarLenStringMemberName_ = string.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string T_RequiredVarLenStringMemberName_
        {
            get => IfUnpacked(_T_RequiredVarLenStringMemberName_);
            set => _T_RequiredVarLenStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        public bool Equals(T_EntityImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            if (!_readonlyLocalBlock.Span.SequenceEqual(other._readonlyLocalBlock.Span)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);

    }
}
//##    }
//##}
