//##using System;
//##using System.Linq;
//##using DTOMaker.SrcGen.Core;
//##namespace DTOMaker.SrcGen.MemBlocks;
//###pragma warning disable CS0162 // Unreachable code detected
//##public partial class EntityGenerator
//##{
//##    protected override void OnGenerate(OutputEntity entity)
//##    {
//##        using var entityScope = NewScope(entity);
// <auto-generated>
// Warning: This file was generated by a source generator.
// Changes made to this file will be lost if re-generated.
// </auto-generated>
//##if(false) {
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0162 // Unreachable code detected
//##}
#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#nullable enable
using DataFac.Memory;
using DTOMaker.Models;
using DTOMaker.Runtime.MemBlocks;
using DataFac.Storage;
using System;
using System.Buffers;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using T_ImplNameSpace_;
//##if(false) {
using T_CustomMemberType_ = System.DayOfWeek;
using T_NativeMemberType_ = System.Int32;
namespace DataFac.Memory
{
    public static class Codec_T_NativeMemberType__T_MemberBELE_
    {
        public static T_NativeMemberType_ ReadFromSpan(ReadOnlySpan<byte> source) => Codec_Int32_LE.ReadFromSpan(source);
        public static void WriteToSpan(Span<byte> source, T_NativeMemberType_ value) => Codec_Int32_LE.WriteToSpan(source, value);
    }
}
namespace T_MemberTypeImplSpace_
{
    public class T_MemberTypeImplName_ : EntityBase, T_MemberTypeIntfSpace_.T_MemberTypeIntfName_
    {
        private const int ClassHeight = 1;
        private const int BlockLength = 8;
        private const long StructureCode = 0x00_41L;
        private static readonly BlockHeader _header = BlockHeader.CreateNew(3, StructureCode);

        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeImplName_ source)
        {
            if (source.IsFrozen) return source;
            return new T_MemberTypeImplName_(source);
        }
        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeImplName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }
        public static T_MemberTypeImplName_ CreateRequired(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source)
        {
            if (source is T_MemberTypeImplName_ concrete && concrete.IsFrozen) return concrete;
            return new T_MemberTypeImplName_(source);
        }
        public static T_MemberTypeImplName_? CreateNullable(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }
        public static T_MemberTypeImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)
        {
            return new T_MemberTypeImplName_(buffers);
        }
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;
        public T_MemberTypeImplName_() : base(_header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }
        public T_MemberTypeImplName_(T_MemberTypeImplName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }
        public T_MemberTypeImplName_(T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ source) : base(_header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            this.Field1 = source.Field1;
        }
        protected T_MemberTypeImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(_header, sourceBlocks)
        {
            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];
            if (sourceBlock.Length < BlockLength)
            {
                // source too small - allocate new
                _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
                sourceBlock.CopyTo(_writableLocalBlock);
            }
            else
            {
                _readonlyLocalBlock = sourceBlock;
                _writableLocalBlock = Memory<byte>.Empty;
            }
        }
        public T_MemberTypeImplName_(ReadOnlySequence<byte> buffers) : this(_header, SourceBlocks.ParseFrom(buffers)) { }

        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);
        protected override IEntityBase OnPartCopy() => throw new NotImplementedException();
        protected override int OnGetEntityId() => 3;
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ValueTask OnPack(IDataStore dataStore) => default;
        protected override ValueTask OnUnpack(IDataStore dataStore, int depth) => default;

        public Int64 Field1
        {
            get => Codec_Int64_LE.ReadFromSpan(_readonlyLocalBlock.Slice(0, 8).Span);
            set => Codec_Int64_LE.WriteToSpan(_writableLocalBlock.Slice(0, 8).Span, IfNotFrozen(value));
        }
    }
}
namespace T_BaseImplNameSpace_
{
    public class T_BaseImplName_ : EntityBase, T_BaseIntfNameSpace_.T_BaseIntfName_, IEquatable<T_BaseImplName_>
    {
        private const int T_EntityId_ = 2;
        public new static T_BaseImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)
        {
            SourceBlocks blocks = SourceBlocks.ParseFrom(buffers);
            return blocks.Header.EntityId switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(blocks),
                //##}
                _ => new T_BaseImplNameSpace_.T_BaseImplName_(blocks)
            };
        }

        private const int ClassHeight = 1;
        private const int BlockLength = 4; // structure code = 0x0031L;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        protected override int OnGetEntityId() => 1;
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);
        protected override void OnFreeze()
        {
            base.OnFreeze();
        }

        protected override ValueTask OnPack(IDataStore dataStore)
        {
            return base.OnPack(dataStore);
        }

        protected override ValueTask OnUnpack(IDataStore dataStore, int depth)
        {
            return base.OnUnpack(dataStore, depth);
        }

        protected T_BaseImplName_(BlockHeader header) : base(header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }

        protected T_BaseImplName_(BlockHeader header, T_BaseImplName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseImplName_(BlockHeader header, T_BaseIntfNameSpace_.T_BaseIntfName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            this.BaseField1 = source.BaseField1;
        }

        protected T_BaseImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(header, sourceBlocks)
        {
            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];
            if (sourceBlock.Length < BlockLength)
            {
                // source too small - allocate new
                Memory<byte> memory = new byte[BlockLength];
                sourceBlock.CopyTo(memory);
                _readonlyLocalBlock = memory;
            }
            else
            {
                _readonlyLocalBlock = sourceBlock;
            }
            _writableLocalBlock = Memory<byte>.Empty;
        }

        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0001;
        private const long BlockStructureCode = T_BlockStructureCode_;
        private static readonly BlockHeader _header = BlockHeader.CreateNew(T_EntityId_, BlockStructureCode);
        internal T_BaseImplName_(SourceBlocks sourceBlocks) : this(_header, sourceBlocks) { }

        private const int T_FieldOffset_ = 0;
        private const int T_FieldLength_ = 4;

        public T_NativeMemberType_ BaseField1
        {
            get => (T_NativeMemberType_)Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span);
            set => Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_FieldOffset_, T_FieldLength_).Span, IfNotFrozen(value));
        }

        public bool Equals(T_BaseImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            if (!_readonlyLocalBlock.Span.SequenceEqual(other._readonlyLocalBlock.Span)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_BaseImplName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
    }
}
namespace T_IntfNameSpace_
{
    public interface T_EntityIntfName_ : T_BaseIntfNameSpace_.T_BaseIntfName_
    {
        T_NativeMemberType_? T_NullableNativeStructMemberName_ { get; set; }
        T_CustomMemberType_? T_NullableCustomStructMemberName_ { get; set; }
        T_NativeMemberType_ T_RequiredNativeStructMemberName_ { get; set; }
        T_CustomMemberType_ T_RequiredCustomStructMemberName_ { get; set; }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_NullableEntityMemberName_ { get; set; }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_RequiredEntityMemberName_ { get; set; }
        Octets? T_NullableBinaryMemberName_ { get; set; }
        Octets T_RequiredBinaryMemberName_ { get; set; }
        String? T_NullableStringMemberName_ { get; set; }
        String T_RequiredStringMemberName_ { get; set; }
    }
}
//##}
namespace T_ImplNameSpace_
{
    public partial class T_EntityImplName_ : T_BaseImplNameSpace_.T_BaseImplName_, T_IntfNameSpace_.T_EntityIntfName_, IEquatable<T_EntityImplName_>, IMemBlocksEntity<T_EntityImplName_>
    {
        private sealed class _EntityFactory : IMemBlocksEntityFactory<T_EntityImplName_>
        {
            public T_EntityImplName_ CreateInstance(ReadOnlySequence<byte> buffers) => T_EntityImplName_.DeserializeFrom(buffers);
        }
        private static readonly _EntityFactory _factory = new _EntityFactory();
        public IMemBlocksEntityFactory<T_EntityImplName_> GetFactory() => _factory;
        public static T_EntityImplName_ CreateInstance(ReadOnlySequence<byte> buffers) => T_EntityImplName_.DeserializeFrom(buffers);

        //##if(false) {
        private const int T_ClassHeight_ = 2;
        private const int T_EntityId_ = 2;
        private const int T_BlockLength_ = 1024;
        private const bool T_MemberObsoleteIsError_ = false;
        private const long T_BlockStructureCode_ = 0x0B00 + 0x0030 + 0x0002;
        //##}
        private const long BlockStructureCode = T_BlockStructureCode_;
        private const int ClassHeight = T_ClassHeight_;
        private const int BlockLength = T_BlockLength_;
        private readonly Memory<byte> _writableLocalBlock;
        private readonly ReadOnlyMemory<byte> _readonlyLocalBlock;

        private static readonly BlockHeader _header = BlockHeader.CreateNew(T_EntityId_, BlockStructureCode);

        public new static T_EntityImplName_ CreateRequired(T_EntityImplName_ source)
        {
            if (source.IsFrozen) return source;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_ImplNameSpace_.T_EntityImplName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        public new static T_EntityImplName_? CreateNullable(T_EntityImplName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }

        public new static T_EntityImplName_ CreateRequired(T_IntfNameSpace_.T_EntityIntfName_ source)
        {
            if (source is T_EntityImplName_ concrete && concrete.IsFrozen) return concrete;
            return source switch
            {
                //##foreach(var derived in entity.DerivedEntities.OrderByDescending(e => e.ClassHeight)) {
                //##using var _ = NewScope(derived);
                T_IntfNameSpace_.T_EntityIntfName_ source2 => new T_ImplNameSpace_.T_EntityImplName_(source2),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(source)
            };
        }

        public new static T_EntityImplName_? CreateNullable(T_IntfNameSpace_.T_EntityIntfName_? source)
        {
            return (source is null) ? null : CreateRequired(source);
        }

        public new static T_EntityImplName_ DeserializeFrom(ReadOnlySequence<byte> buffers)
        {
            SourceBlocks blocks = SourceBlocks.ParseFrom(buffers);
            return blocks.Header.EntityId switch
            {
                //##foreach(var derived in entity.DerivedEntities) {
                //##using var _ = NewScope(derived);
                T_EntityId_ => new T_ImplNameSpace_.T_EntityImplName_(blocks),
                //##}
                _ => new T_ImplNameSpace_.T_EntityImplName_(blocks)
            };
        }

        protected override int OnGetEntityId() => T_EntityId_;
        protected override int OnGetClassHeight() => ClassHeight;
        protected override ReadOnlySequenceBuilder<byte> OnSequenceBuilder(ReadOnlySequenceBuilder<byte> builder) => base.OnSequenceBuilder(builder).Append(_readonlyLocalBlock);
        protected override IEntityBase OnPartCopy() => new T_EntityImplName_(this);

        protected override void OnFreeze()
        {
            base.OnFreeze();
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_?.Freeze();
            //##} else {
            _T_RequiredEntityMemberName_?.Freeze();
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##break;
            //##case MemberKind.String:
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override async ValueTask OnPack(IDataStore dataStore)
        {
            await base.OnPack(dataStore);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Pack(dataStore);
            //##} else {
            await T_RequiredEntityMemberName__Pack(dataStore);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            await T_NullableBinaryMemberName__Pack(dataStore);
            //##} else {
            await T_RequiredBinaryMemberName__Pack(dataStore);
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            await T_NullableStringMemberName__Pack(dataStore);
            //##} else {
            await T_RequiredStringMemberName__Pack(dataStore);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        protected override async ValueTask OnUnpack(IDataStore dataStore, int depth)
        {
            await base.OnUnpack(dataStore, depth);
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            await T_NullableEntityMemberName__Unpack(dataStore, depth);
            //##} else {
            await T_RequiredEntityMemberName__Unpack(dataStore, depth);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            await T_NullableBinaryMemberName__Unpack(dataStore);
            //##} else {
            await T_RequiredBinaryMemberName__Unpack(dataStore);
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            await T_NullableStringMemberName__Unpack(dataStore);
            //##} else {
            await T_RequiredStringMemberName__Unpack(dataStore);
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }

        // -------------------- field map -----------------------------
        //  Seq.  Off.  Len.  End.  Type    Name
        //  ----  ----  ----  ----  ------- -------
        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //  T_MemberSequenceR4_  T_FieldOffsetR4_  T_FieldLengthR4_  T_MemberBELE_    T_MemberTypeL7_ T_MemberName_
        //##if(member.Kind == MemberKind.Struct) {
        //        T_FlagsOffsetR4_     1        Byte    T_MemberName_ (flags)
        //##}
        //##}
        // ------------------------------------------------------------

        protected T_EntityImplName_(BlockHeader header) : base(header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }
        public T_EntityImplName_() : base(_header)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
        }

        protected T_EntityImplName_(BlockHeader header, T_EntityImplName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;
            //##} else {
            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;
            //##} else {
            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source._T_NullableEntityMemberName_;
            //##} else {
            _T_RequiredEntityMemberName_ = source._T_RequiredEntityMemberName_;
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source._T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source._T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source._T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source._T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }
        public T_EntityImplName_(T_EntityImplName_ source) : this(_header, source) { }

        protected T_EntityImplName_(BlockHeader header, T_IntfNameSpace_.T_EntityIntfName_ source) : base(header, source)
        {
            _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
            //##foreach (var member in entity.Members) {
            //##using var _ = NewScope(entity, member);
            //##switch(member.Kind) {
            //##case MemberKind.Struct:
            //##if (member.IsNullable) {
            //##if (member.IsCustom) {
            this.T_NullableCustomStructMemberName_ = source.T_NullableCustomStructMemberName_;
            //##} else {
            this.T_NullableNativeStructMemberName_ = source.T_NullableNativeStructMemberName_;
            //##}
            //##} else {
            //##if (member.IsCustom) {
            this.T_RequiredCustomStructMemberName_ = source.T_RequiredCustomStructMemberName_;
            //##} else {
            this.T_RequiredNativeStructMemberName_ = source.T_RequiredNativeStructMemberName_;
            //##}
            //##}
            //##break;
            //##case MemberKind.Entity:
            //##if (member.IsNullable) {
            _T_NullableEntityMemberName_ = source.T_NullableEntityMemberName_ is null ? null : T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(source.T_NullableEntityMemberName_);
            //##} else {
            _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(source.T_RequiredEntityMemberName_);
            //##}
            //##break;
            //##case MemberKind.Binary:
            //##if (member.IsNullable) {
            _T_NullableBinaryMemberName_ = source.T_NullableBinaryMemberName_;
            //##} else {
            _T_RequiredBinaryMemberName_ = source.T_RequiredBinaryMemberName_;
            //##}
            //##break;
            //##case MemberKind.String:
            //##if (member.IsNullable) {
            _T_NullableStringMemberName_ = source.T_NullableStringMemberName_;
            //##} else {
            _T_RequiredStringMemberName_ = source.T_RequiredStringMemberName_;
            //##}
            //##break;
            //##default:
            //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
            //##break;
            //##} // switch
            //##}
        }
        public T_EntityImplName_(T_IntfNameSpace_.T_EntityIntfName_ source) : this(_header, source) { }

        protected T_EntityImplName_(BlockHeader header, SourceBlocks sourceBlocks) : base(header, sourceBlocks)
        {
            var sourceBlock = sourceBlocks.Blocks.Span[ClassHeight];
            if (sourceBlock.Length < BlockLength)
            {
                // source too small - allocate new
                _readonlyLocalBlock = _writableLocalBlock = new byte[BlockLength];
                sourceBlock.CopyTo(_writableLocalBlock);
            }
            else
            {
                _readonlyLocalBlock = sourceBlock;
                _writableLocalBlock = Memory<byte>.Empty;
            }
        }
        internal T_EntityImplName_(SourceBlocks sourceBlocks) : this(_header, sourceBlocks) { }
        public T_EntityImplName_(ReadOnlySequence<byte> buffers) : this(_header, SourceBlocks.ParseFrom(buffers)) { }

        //##if(false) {
        private const int T_RequiredNativeStructFieldOffset_ = 0;
        private const int T_RequiredCustomStructFieldOffset_ = 4;
        private const int T_NullableCustomStructFieldOffset_ = 8;
        private const int T_NullableNativeStructFieldOffset_ = 12;
        private const int T_RequiredCustomStructFlagsOffset_ = 16;
        private const int T_RequiredNativeStructFlagsOffset_ = 17;
        private const int T_NullableCustomStructFlagsOffset_ = 18;
        private const int T_NullableNativeStructFlagsOffset_ = 19;

        private const int T_NullableEntityFieldOffset_ = 64;
        private const int T_RequiredEntityFieldOffset_ = 128;

        private const int T_NullableBinaryFieldOffset_ = 256;
        private const int T_RequiredBinaryFieldOffset_ = 320;

        private const int T_NullableStringFieldOffset_ = 448;
        private const int T_RequiredStringFieldOffset_ = 512;

        private const int T_FieldLength_ = 4;
        private const bool T_IsBigEndian_ = false;
        //##}
        //##foreach (var member in entity.Members) {
        //##using var _ = NewScope(entity, member);
        //##switch(member.Kind) {
        //##case MemberKind.Struct:
        //##if (member.IsNullable) {
        //##if (member.IsCustom) {
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_CustomMemberType_? T_NullableCustomStructMemberName_
        {
            get
            {
                byte flags = Codec_Byte_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableCustomStructFlagsOffset_, 1).Span);
                if (flags == 0) return null;
                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span);
                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);
            }
            set
            {
                ThrowIfFrozen();
                if (value.HasValue)
                {
                    Codec_Byte_LE.WriteToSpan(_writableLocalBlock.Slice(T_NullableCustomStructFlagsOffset_, 1).Span, 1);
                    T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value.Value);
                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);
                }
                else
                {
                    Codec_Byte_LE.WriteToSpan(_writableLocalBlock.Slice(T_NullableCustomStructFlagsOffset_, 1).Span, 0);
                    _writableLocalBlock.Slice(T_NullableCustomStructFieldOffset_, T_FieldLength_).Span.Clear();
                }
            }
        }
        //##} else {
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_NativeMemberType_? T_NullableNativeStructMemberName_
        {
            get
            {
                byte flags = Codec_Byte_LE.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableNativeStructFlagsOffset_, 1).Span);
                if (flags == 0) return null;
                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span);
            }
            set
            {
                ThrowIfFrozen();
                if (value.HasValue)
                {
                    Codec_Byte_LE.WriteToSpan(_writableLocalBlock.Slice(T_NullableNativeStructFlagsOffset_, 1).Span, 1);
                    Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span, value.Value);
                }
                else
                {
                    Codec_Byte_LE.WriteToSpan(_writableLocalBlock.Slice(T_NullableNativeStructFlagsOffset_, 1).Span, 0);
                    _writableLocalBlock.Slice(T_NullableNativeStructFieldOffset_, T_FieldLength_).Span.Clear();
                }
            }
        }
        //##}
        //##} else {
        //##if (member.IsCustom) {
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_CustomMemberType_ T_RequiredCustomStructMemberName_
        {
            get
            {
                T_NativeMemberType_ nativeValue = Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span);
                return T_ConverterSpace_.T_ConverterName_.ToCustom(nativeValue);
            }
            set
            {
                ThrowIfFrozen();
                Codec_Byte_LE.WriteToSpan(_writableLocalBlock.Slice(T_RequiredCustomStructFlagsOffset_, 1).Span, 1);
                T_NativeMemberType_ nativeValue = T_ConverterSpace_.T_ConverterName_.ToNative(value);
                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredCustomStructFieldOffset_, T_FieldLength_).Span, nativeValue);
            }
        }
        //##} else {
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_NativeMemberType_ T_RequiredNativeStructMemberName_
        {
            get
            {
                return Codec_T_NativeMemberType__T_MemberBELE_.ReadFromSpan(_readonlyLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span);
            }
            set
            {
                ThrowIfFrozen();
                Codec_Byte_LE.WriteToSpan(_writableLocalBlock.Slice(T_RequiredNativeStructFlagsOffset_, 1).Span, 1);
                Codec_T_NativeMemberType__T_MemberBELE_.WriteToSpan(_writableLocalBlock.Slice(T_RequiredNativeStructFieldOffset_, T_FieldLength_).Span, value);
            }
        }
        //##}
        //##}
        //##break;
        //##case MemberKind.Entity:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableEntityMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            if (_T_NullableEntityMemberName_ is not null)
            {
                await _T_NullableEntityMemberName_.Pack(dataStore);
                var buffers = _T_NullableEntityMemberName_.GetBuffers();
                blobId = await dataStore.PutBlob(buffers);
            }
            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span);
        }
        private async ValueTask T_NullableEntityMemberName__Unpack(IDataStore dataStore, int depth)
        {
            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_NullableEntityFieldOffset_, 64).Span);
            var blob = await dataStore.GetBlob(blobId);
            _T_NullableEntityMemberName_ = null;
            if (blob is not null)
            {
                _T_NullableEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(blob.Value);
                await _T_NullableEntityMemberName_.Unpack(dataStore, depth - 1);
            }
        }
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_NullableEntityMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_? T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_? T_IntfNameSpace_.T_EntityIntfName_.T_NullableEntityMemberName_
        {
            get => IfUnpacked(_T_NullableEntityMemberName_);
            set => _T_NullableEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateNullable(value));
        }
        //##} else {
        private async ValueTask T_RequiredEntityMemberName__Pack(IDataStore dataStore)
        {
            if (_T_RequiredEntityMemberName_ is null)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore);
            }
            await _T_RequiredEntityMemberName_.Pack(dataStore);
            var buffers = _T_RequiredEntityMemberName_.GetBuffers();
            BlobIdV1 blobId = await dataStore.PutBlob(buffers);
            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span);
        }
        private async ValueTask T_RequiredEntityMemberName__Unpack(IDataStore dataStore, int depth)
        {
            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_RequiredEntityFieldOffset_, 64).Span);
            var blob = await dataStore.GetBlob(blobId);
            if (blob is null)
            {
                _T_RequiredEntityMemberName_ = await CreateEmpty<T_MemberTypeImplSpace_.T_MemberTypeImplName_>(dataStore);
            }
            else
            {
                _T_RequiredEntityMemberName_ = T_MemberTypeImplSpace_.T_MemberTypeImplName_.DeserializeFrom(blob.Value);
                await _T_RequiredEntityMemberName_.Unpack(dataStore, depth - 1);
            }
        }
        private T_MemberTypeImplSpace_.T_MemberTypeImplName_? _T_RequiredEntityMemberName_ = null;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public T_MemberTypeImplSpace_.T_MemberTypeImplName_ T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(value);
        }
        T_MemberTypeIntfSpace_.T_MemberTypeIntfName_ T_IntfNameSpace_.T_EntityIntfName_.T_RequiredEntityMemberName_
        {
            get => IfNotNull(IfUnpacked(_T_RequiredEntityMemberName_));
            set => _T_RequiredEntityMemberName_ = IfNotFrozen(T_MemberTypeImplSpace_.T_MemberTypeImplName_.CreateRequired(value));
        }
        //##}
        //##break;
        //##case MemberKind.Binary:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableBinaryMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = _T_NullableBinaryMemberName_ is null
                ? default
                : await dataStore.PutBlob(_T_NullableBinaryMemberName_.Sequence);
            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64).Span);
        }
        private async ValueTask T_NullableBinaryMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_NullableBinaryFieldOffset_, 64).Span);
            var blob = await dataStore.GetBlob(blobId);
            _T_NullableBinaryMemberName_ = blob is null ? null : Octets.UnsafeWrap(blob.Value);
        }
        private Octets? _T_NullableBinaryMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets? T_NullableBinaryMemberName_
        {
            get => IfUnpacked(_T_NullableBinaryMemberName_);
            set => _T_NullableBinaryMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredBinaryMemberName__Pack(IDataStore dataStore)
        {
            var buffers = _T_RequiredBinaryMemberName_.Sequence;
            BlobIdV1 blobId = await dataStore.PutBlob(buffers);
            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64).Span);
        }
        private async ValueTask T_RequiredBinaryMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_RequiredBinaryFieldOffset_, 64).Span);
            var blob = await dataStore.GetBlob(blobId);
            _T_RequiredBinaryMemberName_ = blob is null ? Octets.Empty : Octets.UnsafeWrap(blob.Value);

        }
        private Octets _T_RequiredBinaryMemberName_ = Octets.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public Octets T_RequiredBinaryMemberName_
        {
            get => IfUnpacked(_T_RequiredBinaryMemberName_);
            set => _T_RequiredBinaryMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##case MemberKind.String:
        //##if (member.IsNullable) {
        private async ValueTask T_NullableStringMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = _T_NullableStringMemberName_ is null
                ? default
                : blobId = await dataStore.PutBlob(new ReadOnlySequence<byte>(System.Text.Encoding.UTF8.GetBytes(_T_NullableStringMemberName_)));
            blobId.WriteTo(_writableLocalBlock.Slice(T_NullableStringFieldOffset_, 64).Span);
        }
        private async ValueTask T_NullableStringMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_NullableStringFieldOffset_, 64).Span);
            var blob = await dataStore.GetBlob(blobId);
#if NET8_0_OR_GREATER
            _T_NullableStringMemberName_ = blob is null ? null : System.Text.Encoding.UTF8.GetString(blob.Value);
#else
            _T_NullableStringMemberName_ = blob is null ? null : System.Text.Encoding.UTF8.GetString(blob.Value.ToArray());
#endif
        }
        private string? _T_NullableStringMemberName_;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string? T_NullableStringMemberName_
        {
            get => IfUnpacked(_T_NullableStringMemberName_);
            set => _T_NullableStringMemberName_ = IfNotFrozen(value);
        }
        //##} else {
        private async ValueTask T_RequiredStringMemberName__Pack(IDataStore dataStore)
        {
            BlobIdV1 blobId = default;
            var buffers = new ReadOnlySequence<byte>(System.Text.Encoding.UTF8.GetBytes(_T_RequiredStringMemberName_));
            blobId = await dataStore.PutBlob(buffers);
            blobId.WriteTo(_writableLocalBlock.Slice(T_RequiredStringFieldOffset_, 64).Span);
        }
        private async ValueTask T_RequiredStringMemberName__Unpack(IDataStore dataStore)
        {
            BlobIdV1 blobId = BlobIdV1.FromSpan(_readonlyLocalBlock.Slice(T_RequiredStringFieldOffset_, 64).Span);
            var blob = await dataStore.GetBlob(blobId);
#if NET8_0_OR_GREATER
            _T_RequiredStringMemberName_ = blob is null ? string.Empty : System.Text.Encoding.UTF8.GetString(blob.Value);
#else
            _T_RequiredStringMemberName_ = blob is null ? string.Empty : System.Text.Encoding.UTF8.GetString(blob.Value.ToArray());
#endif
        }
        private string _T_RequiredStringMemberName_ = string.Empty;
        //##if(member.IsObsolete) {
        [Obsolete("T_MemberObsoleteMessage_", T_MemberObsoleteIsError_)]
        //##}
        public string T_RequiredStringMemberName_
        {
            get => IfUnpacked(_T_RequiredStringMemberName_);
            set => _T_RequiredStringMemberName_ = IfNotFrozen(value);
        }
        //##}
        //##break;
        //##default:
        //##Emit($"#error Implementation for MemberKind '{member.Kind}' is missing");
        //##break;
        //##} // switch

        //##}

        public bool Equals(T_EntityImplName_? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            if (!base.Equals(other)) return false;
            if (!_readonlyLocalBlock.Span.SequenceEqual(other._readonlyLocalBlock.Span)) return false;
            return true;
        }
        public override bool Equals(object? obj) => obj is T_EntityImplName_ other && Equals(other);
        public override int GetHashCode() => base.GetHashCode();
        public static bool operator ==(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? left.Equals(right) : (right is null);
        public static bool operator !=(T_EntityImplName_? left, T_EntityImplName_? right) => left is not null ? !left.Equals(right) : (right is not null);

    }
}
//##    }
//##}
